### PR TITLE
Fix .cpppp when passing .hpp header name

### LINKED ISSUE #44: Using `.hpp` for header filename causes `.cpppp` for source file
It makes sense that `foo.h` leads to `foo.cpp` but `foo.hpp` now also leads to `foo.cpp`.

Command:

```console
$ dd if=/dev/urandom bs=1M count=10 of=data.bin
$ bin2cpp --file=data.bin --headerfile="foo.hpp" --output=. --identifier=Foo
bin2cpp v2.4.0 - Convert binary files into C++ source code.
Copyright (C) 2013-2021 end2endzone.com. All rights reserved.
bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp 
Embedding "data.bin"...
Writing file "./foo.hpp"...
Writing file "./foo.cpppp"...
```

### PR DESCRIPTION
**Pull request by MatthewScholefield**
This fixes #44.

### CODE REVIEW

**Comment by end2endzone** [comment]
I have reviewed changes of PR #46 and I fully agree with the correction.

However, github was unable to run the automated tests on GitHub Actions. It fails at a step where an svn badge is uploaded to [one of my gist](https://gist.github.com/end2endzone/58cf6c72c08e706335337d5ef9ca48e8). This is certainly related to a security issue. It is working fine when my own commits trigger builds but I guess that when someone else triggers a build, it fails for an unknown reason.

I would like to take this opportunity to look at this and prevent future failures in other PR. Please allow me some time to look at it. I need to find out why the token used to upload to my gist does not work in other users PR. If you have any hint about this, I am open to suggestions.

**Comment by MatthewScholefield** [comment]
I believe the problem is just that GitHub Actions doesn't use your secrets when running tests on my fork because that would allow anyone to change the test code to print the secrets. So I would suggest seeing if you could make any necessary secrets optional.

**Comment by end2endzone** [comment]
You are right. From the [project's Actions secrets page](https://github.com/end2endzone/bin2cpp/settings/secrets/actions): "_Secrets are not passed to workflows that are triggered by a pull request from a fork. [Learn more](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)._".

I would prefer to only disable badge uploads step when running PR checks and keep building and testing proposed PR. I am currently looking for an `if` statements that would skip theses step when the workflow is run from a PR.

**Comment by end2endzone** [comment]
I documented the fix in #48 and committed the changes in my repository in commit 1e37ab1e73fb4f495cb8f533e9906b7694db8d16. Note that I have not tried the changes on an actual PR but I think it should be working according to [this](https://stackoverflow.com/questions/66205887/only-run-github-actions-step-if-not-a-pull-request). 

The checks in this push request seems to be running from a temporary commit 2d37df224733e4c3b4142037a9251b56425937bb , `2d37df224733e4c3b4142037a9251b56425937bb:refs/remotes/pull/46/merge`, according to command `git log -1 --format='%H'` in the logs. After I have committed 1e37ab1e73fb4f495cb8f533e9906b7694db8d16 to my master branch, I though that I would be able to re-run the checks again on master (including the latest commits) and get a "pass" result. But it does not seems to work that way. I will try options mentioned [here](https://stackoverflow.com/questions/52408592/how-to-relaunch-github-check-without-pushing-new-commits/). If it does not work, I will just stop trying and just accept the pull request and hope that next PR I get will be easier to manage.

**Comment by end2endzone** [comment]
woot!

**Pull request merged**
